### PR TITLE
Fixes #59

### LINKED ISSUE #59: Verify & Implement Mutation: likes/ADD_LIKE
#### Function to implement:

Mutation: likes/ADD_LIKE

Things to note:

-   [ ] Ensure different branch for each issue.
-   [ ] Rebase frequently to avoid conflicts later on
-   [ ] Try to ensure only a couple of commits
-   [ ] Test your code thoroughly before pushing
-   [ ] Add to description, "Fixes #issue-no, eg: Fixes #x (where #x is the issue id)
-   [ ] Work to be done on template branch. i.e. you need to checkout the template branch on your local computer and PR should be to the template branch

### PR DESCRIPTION
**Pull request by kush-garg**
[IMPLEMENT] mutation: likes/ADD_LIKE

### CODE REVIEW

**Comment by gsc2001** [comment]
`Fixes line` should be in PR comment not heading. And IMPLEMENT is basically ADD. What you wrote in your comment should be your heading and your heading should be comment

**Comment by gsc2001** [comment]
The upper four commits should not come, did you not start with template as your base.

**Comment by gsc2001** [comment]
implementation seems fine to me @Pk13055 .  But please remove these upper four commits. This should not be added into template branch

**Comment by Pk13055** [comment]
Additionally you can just do changes and force-push, you don’t need to close PRs and reopen them.

**Pull request closed without merging**
