### PR TITLE
Implemented issue #60: DEL_LIKE mutation

### PR DESCRIPTION
**Pull request by RajWorking**
please merge

### CODE REVIEW

**Comment by kjain1810** [comment]
Add fixes #{issue no} as description

**Comment by Pk13055** [comment]
Fixes #60

**Comment by Pk13055** [comment]
Rebase and squash the 3 commits into one

**Comment by kjain1810** [comment]
@Pk13055 umm, following those commands exactly reverted changes of the previous commits i think

**Comment by RajWorking** [comment]
Fixes #63 #60

**Comment by Pk13055** [comment]
You committed the same thing

**Pull request merged**
